### PR TITLE
changed mongodb connection and fixed email registration

### LINKED ISSUE #46: Wrong user profile info
**Describe the bug**
If we use email id like LCS2019015@gmail.com, then also it saves the roll no and branch.

**To Reproduce**
1. Go to Login with G+
2. Login with email id like LIT2019009@gmail.com
3. go to user profile

### PR DESCRIPTION
**Pull request by narendraiiitl**
### Issues solved in this PR
Fixes #46 

### List of developments
Improved code for database connection to resist data loss in case our app crashes.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,2 +1,3 @@
 /node_modules
 /config
+/rest.http
```
Comment (blurry-x-face) [inline .gitignore:3]: What is this used for?

File: db/mongoose.js [hunk 2]
```diff
@@ -1,13 +1,35 @@
...
+});
+
+mongoose.connection.on("disconnected", () => {
+  console.log("Mongoose Disconnected");
+});
+
+process.on("SIGINT", async () => {
+  await mongoose.connection.close();
+  process.exit(0);
+});
```
Comment (blurry-x-face) [inline db/mongoose.js:35]: Could you brief a little more about this?

File: db/mongoose.js [hunk 3]
```diff
@@ -1,13 +1,35 @@
...
-    } else {
-      console.log("MongoDB Connected");
-    }
-  }
-);
+mongoose
+  .connect(keys.mongoURI, {
+    useNewUrlParser: true,
+    useUnifiedTopology: true,
+    dbName: "Messportal",
```
Comment (blurry-x-face) [inline db/mongoose.js:7]: I guess we can leave the DB name to be configured with the help of MONGO_URI, what do you think?

Comment (narendraiiitl) [reply db/mongoose.js:7]: Its just about preference nothing else.

File: db/mongoose.js (hunk 2 above)
Comment (narendraiiitl) [reply db/mongoose.js:35]: when the server is closed forcefully or because of some error, the transactions that are mode using mongoose are also closed instantaneously which causes the loss of data. so it just takes care of the mongoose process to finish and then close the program.

File: .gitignore (hunk 1 above)
Comment (narendraiiitl) [reply .gitignore:3]: its just an alternative of postman for testing purpose in vs code.

File: db/mongoose.js (hunk 3 above)
Comment (blurry-x-face) [reply db/mongoose.js:7]: Can you then just update the PR to remove this configuration? Rest looks good to me.

**Review by rishabhshuklax — APPROVED** [review]

**Comment by rishabhshuklax** [comment]
Thanks @narendraiiitl !
